# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wKKkzqUOo8t3_7GfgnrWcVBmr26bm3Ui
"""

import sys
!{sys.executable} -m pip install pandas
!{sys.executable} -m pip install python-docx
!{sys.executable} -m pip install streamlit
!{sys.executable} -m pip install openpyxl